### ISSUE TITLE
impression callback is continuously called at refreshInterval if real time updates are made

### ISSUE THREAD

**Issue by spgandhi** [Unleash/proxy-client-react#126]
### Describe the bug

I am using `@unleash/proxy-client-react` in a react-native app. I have setup a impression listener in a root level react component so that I can track events in our data lake 

```
useEffect(() => {
    console.warn('SPG_UNLEASH_CLIENT_EVENT');
    unleash.on('impression', (event: any) => {
      // track event in data lake
      if (__DEV__) {
        console.log('UNLEASH_IMPRESSION', event);
      }
    });
  }, []);
  ```

I have set `refetchInterval` to `15`

When I start the app, impressions callbacks are called as expected for each flag I try to access.

If I update a flag (say if I turn off a flag), then at the 15 sec interval that particular flag will be updated and I will see another impression event. And at each 15 sec interval the impression callback will be called even if the value has not been updated

### Expected behavior

The impression callback should be called on initial app load. And then it should only be called once when the value is updated

### Screenshots

<img width="1231" alt="Screenshot 2023-07-24 at 4 39 00 PM" src="https://github.com/Unleash/proxy-client-react/assets/5814269/55fb2fda-691d-4f4b-9472-bd5600ca791d">

### Unleash version

Unleash 5.1.8 (Open Source)

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

@unleash/proxy-client-react": "^3.6.0"

**Comment by spgandhi** [comment]
I added `impressionDataAll: true` to the config and noted that the impression callbacks are called for all the flags at 15 second interval (I have set `refetchInterval` to `15`) once any of the flag is updated

**Comment by spgandhi** [comment]
Also noted that for some of the callbacks, the data has `impressionData: undefined` - although all my flags have impression data enabled. Only the flag was actually updated has `impressionData: true`

<img width="1228" alt="Screenshot 2023-07-24 at 4 55 43 PM" src="https://github.com/Unleash/proxy-client-react/assets/5814269/8a0df2c6-bd0f-4ed9-9ed0-a4c886e39859">

**Comment by thomasheartman** [comment]
Hey, @spgandhi! Thanks for reporting this. I've looked into it a bit and I think it might be working as expected, but I'd like some more info from you.

> If I update a flag (say if I turn off a flag), then at the 15 sec interval that particular flag will be updated and I will see another impression event. And at each 15 sec interval the impression callback will be called even if the value has not been updated

The impression event shouldn't fire for flags that aren't accessed. You can confirm that by adding another flag that's enabled but never checked in your code.

The reason you're seeing the impression callback every 15 seconds is probably that your components are re-rendered because the state changes. This causes the flags to be checked again, triggering an additional impression event.

You can verify this by using a flag in a component that isn't rendered. You should see that no impression events fire for that even if the configuration changes.

> The impression callback should be called on initial app load. And then it should only be called once when the value is updated

This isn't quite how impression events are work. An event should fire every time you check a flag, not when the configuration changes. The reason you're seeing them fire every 15 seconds is as outlined previously.

What's your use case? Or rather, why are you expecting them to work like this? It might be something we've overlooked?

> Also noted that for some of the callbacks, the data has impressionData: undefined - although all my flags have impression data enabled. Only the flag was actually updated has impressionData: true

Yes, that's correct. When you check a flag that isn't enabled, the SDK doesn't have any configuration for it, so we can't know whether `impressionData` is enabled or not. As such, flags that aren't enabled always have `impressionData: undefined`. That appears to be consistent with your screenshot. 

---

So overall, I think this is working as expected, but that there may be some misgivings related to how it should work. 

However, I think that it'd make sense for us not to cause components to rerender if there is no toggle state change to keep us from creating more impression events than necessary. I'll see if we want to look into that.

What do you think?

**Comment by spgandhi** [comment]
@thomasheartman thanks for the detailed response.

I understand that the impression event should be fired every time a flag is checked. And that is what I would expect. But I wanted to clarify about what I am experiencing - 

These are 2 separate scenarios that I am experiencing - 

1. I open the app. All flags that are being checked fire an impression event. That's it. After that I am guessing at every `refetchInterval` interval (which is 15 sec in my case), Unleash SDK might be polling the Unleash Proxy, but there are no impression events or any component re-render. That is the happy case

2. In this scenario - I open the app. All flags that are being checked fire an impression event. Great so far. Now, say 2 mins later, if I toggle a flag in the Admin UI, then at the next `refetchInterval`, all the impression events will fire again. Ideally I would expect only the flag that toggled to fire the impression event. But maybe with a toggle change the whole `FlagProvider` context updates - re-rendering all the children and so all flags are checked again which leads to impression event for all flags. 

But after this, at every `refreshInterval` all the impression events will fire again and will continue to do so at every `refreshInterval`. This behavior is what is unexpected and perhaps a bug.

**Comment by thomasheartman** [comment]
Thanks for getting back to me! Upon re-reading your original question, I think it might be because you're using this in a React Native setting. Can you create a repro repo that demonstrates this in as simple as way a possible? That'd help us narrow down and find out what might be going wrong.

> These are 2 separate scenarios that I am experiencing -
>
> 1. I open the app. All flags that are being checked fire an impression event. That's it. After that I am guessing at every refetchInterval interval (which is 15 sec in my case), Unleash SDK might be polling the Unleash Proxy, but there are no impression events or any component re-render. That is the happy case

Interesting, so there's no re-rendering happening in the meantime? Just wanna double-check, because that's what I saw in the regular web-version of React. It might behave differently in React Native.

> 2. In this scenario - I open the app. All flags that are being checked fire an impression event. Great so far. Now, say 2 mins later, if I toggle a flag in the Admin UI, then at the next refetchInterval, all the impression events will fire again. Ideally I would expect only the flag that toggled to fire the impression event. But maybe with a toggle change the whole FlagProvider context updates - re-rendering all the children and so all flags are checked again which leads to impression event for all flags.

Yeah, I think your assessment here is correct. If a flag changes, the existing flag context is overwritten, so even if the specific flag you're using hasn't changed, the parent object has changed, and this probably forces a re-render.

> But after this, at every refreshInterval all the impression events will fire again and will continue to do so at every refreshInterval. This behavior is what is unexpected and perhaps a bug.

Now this is interesting, though. Just to be clear, you're saying that this behavior **does not happen until you change a toggle and update the context**? Before that impression events are not triggered periodically (`refreshInterval`)?

Anyway, I think it makes sense that a context update shouldn't trigger re-renders (and thus impression events) for flags that don't change.

If I might ask: what's your use case? What are you wanting to use the impression events for? Do the extra triggering of the events skew your results somehow?

**Comment by thomasheartman** [comment]
Closing this after 7 months of inactivity. Re-open if new information surfaces.
