### ISSUE TITLE
startClient not working as expected

### ISSUE THREAD

**Issue by duveborg** [Unleash/proxy-client-react#163]
### Describe the bug

`<FlagProvider startClient={false}>`

Providing false here seem to fire network requests to fetch flags. Is that expected?

### Subscription type

None

### Hosting type

None

**Comment by FredrikOseberg** [comment]
> ### Describe the bug
> `<FlagProvider startClient={false}>`
> 
> Providing false here seem to fire network requests to fetch flags. Is that expected?
> 
> ### Steps to reproduce the bug
> _No response_
> 
> ### Expected behavior
> _No response_
> 
> ### Logs, error output, etc.
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Unleash version
> _No response_
> 
> ### Subscription type
> None
> 
> ### Hosting type
> None
> 
> ### SDK information (language and version)
> _No response_

Hello. If you are not passing a custom client and on a version less than 4.2.2 it is expected, because it previously only applied if you passed a custom client. In 4.2.2 we [merged this PR](https://github.com/Unleash/proxy-client-react/pull/162) which also makes this functionality work with passing a config. Be aware that if you are passing a config there is no way to start the client afterwards.
