### ISSUE TITLE
regarding the documentation for using the custom activation strategy

### ISSUE THREAD

**Issue by santhosh-challa** [Unleash/proxy-client-react#25]
I am struggling to update the context in case of using a custom activation strategy. I went through the documentation and did not find any examples there. There exists one example for Node though. It was mentioned that clients provide the abstraction for using the custom activation strategies, but I could not figure out how. If there are any pointers for the same would be greatly helpful. For now, I am using existing strategies with different values to match my need.

**Comment by rsoliveira2018** [comment]
@santhosh-challa I am also looking for a way to work with the strategies defined in the Unleash UI and I have found none so far. Can you show me somehow they way you are dealing with the strategies in the frontend? Thanks in advance.

**Comment by FredrikOseberg** [comment]
> I am struggling to update the context in case of using a custom activation strategy. I went through the documentation and did not find any examples there. There exists one example for Node though. It was mentioned that clients provide the abstraction for using the custom activation strategies, but I could not figure out how. If there are any pointers for the same would be greatly helpful. For now, I am using existing strategies with different values to match my need.

Hi. In order to create a custom strategy for the client side you need to add it to the [unleash-proxy](https://github.com/Unleash/unleash-proxy). It will accept a `customStrategies` field or environment variable: UNLEASH_CUSTOM_STRATEGIES_FILE that takes an array of paths to exported javascript strategies. Are you running your own proxy?


<br class="Apple-interchange-newline">

**Comment by FredrikOseberg** [comment]
> @santhosh-challa I am also looking for a way to work with the strategies defined in the Unleash UI and I have found none so far. Can you show me somehow they way you are dealing with the strategies in the frontend? Thanks in advance.

Is this related to custom strategies?

**Comment by rsoliveira2018** [comment]
Hi, @FredrikOseberg. Nope. I had misunderstood and by now we have made it work with the standard strategies. Thanks anyway.

**Comment by santhosh-challa** [comment]
> 

Thanks for the pointer, I will check that. Is that documented somewhere? Currently, we are running our won proxy.

**Comment by FredrikOseberg** [comment]
> > > I am struggling to update the context in case of using a custom activation strategy. I went through the documentation and did not find any examples there. There exists one example for Node though. It was mentioned that clients provide the abstraction for using the custom activation strategies, but I could not figure out how. If there are any pointers for the same would be greatly helpful. For now, I am using existing strategies with different values to match my need.
> > 
> > 
> > Hi. In order to create a custom strategy for the client side you need to add it to the [unleash-proxy](https://github.com/Unleash/unleash-proxy). It will accept a `customStrategies` field or environment variable: UNLEASH_CUSTOM_STRATEGIES_FILE that takes an array of paths to javascript files with the exported strategies you have written. Are you running your own proxy?
> 
> Thanks for the pointer, I will check that. Is that documented somewhere? Currently, we are running our won proxy.

I think you have found a weakness in our documentation and I have alerted our excellent community manager @thomasheartman  who is currently working on updating this. In the meantime, I've looked at the code and it seems that if you provide a filepath to file that exports an array of instantiated strategies that should work. Something like this: 

```js
// customStrategies.js

class MyCustomStrategy extends Strategy {
    //...
}

export default [new MyCustomStrategy()]
```

**Comment by FredrikOseberg** [comment]
> Ok, thanks for the example. I will check this. Thanks for the quick help!

No problem. Closing this for now, if you still have issues please let me know.

**Comment by thomasheartman** [comment]
Hey, folks! Just wanted to chime in and say that the updated documentation is well underway, but due to Christmas holidays it likely won't be released until January. In the meantime, feel free to check out [the PR](https://github.com/Unleash/unleash/pull/1205 "Add more docs on custom strategies and the proxy") and [the prerendered update](https://unleash-docs-git-docs-proxy-and-custom-strategies-unleash-team.vercel.app/). 

I've updated the [Custom Activation Strategies](https://unleash-docs-git-docs-proxy-and-custom-strategies-unleash-team.vercel.app/advanced/custom_activation_strategy) section, [the Unleash Proxy docs](https://unleash-docs-git-docs-proxy-and-custom-strategies-unleash-team.vercel.app/sdks/unleash-proxy#custom-activation-strategies), and added a new ["How to use custom activation strategies"](https://unleash-docs-cz8f9orai-unleash-team.vercel.app/how-to/how-to-use-custom-strategies) document. 

@santhosh-challa Feel free to check it out if you have time; I'd love some outside feedback on this as well: do the new updates make sense?

Note that I haven't had it reviewed yet, so there may still be some minor errors hanging about that'll get fixed before we release.

**Comment by santhosh-challa** [comment]
Hi @thomasheartman thanks for your efforts in making the documentation great!. I just quickly looked at it. Everything looks good! I have a doubt only at the below statement in  "[How to use custom activation strategies](https://unleash-docs-cz8f9orai-unleash-team.vercel.app/how-to/how-to-use-custom-strategies)" document:

You mentioned that:

> Front-end client SDK don't evaluate strategies directly, so you need to implement the custom strategy in the Unleash Proxy. The below steps assume you're running the Unleash Proxy as a Docker container. If you're running the Unleash Proxy via Node directly, follow the steps for server-side SDKs instead.

I felt a little disconnected here. If we are running the proxy using node, the example code looks like this:

```
const app = createApp({
    unleashUrl: 'https://app.unleash-hosted.com/demo/api/',
    unleashApiToken: '56907a2fa53c1d16101d509a10b78e36190b0f918d9f122d',
    proxySecrets: ['proxy-secret', 'another-proxy-secret', 's1'],
    refreshInterval: 1000,
    // logLevel: 'info',
    // projectName: 'order-team',
    // environment: 'development',
});
```
And you mentioned referring to the previous step, which is talking about using unleash on the server side, not setting up unleash proxy using node, right?

I feel if we have another section option B and to show an example passing custom strategies to `createApp` would make it perfect. Am I making sense? Please let me know if I am not making a point here.

Thanks!

**Comment by thomasheartman** [comment]
@santhosh-challa Yeah, that's great input! I was wondering about that too. Thanks for letting me know; I'll sort it out 😄

**Comment by thomasheartman** [comment]
@santhosh-challa Thanks again for the input 🙏🏼 I've added an extra [section on using custom strategies with the proxy when running it via Node](https://docs.getunleash.io/how-to/how-to-use-custom-strategies#step-3-b-node) now. Thanks for helping us make the docs better. And any more feedback you've got is always welcome 😄
