### ISSUE TITLE
useUnleashedContext does not expose key context members

### ISSUE THREAD

**Issue by jtaaa** [Unleash/proxy-client-react#42]
Hi 👋

As far as I can tell, this package does not currently support a way to extract the current value of all flags. This is useful for providing context for A/B testing and analytics. There also seems to be no way to access the underlying unleashed js SDK client which exposes the `getAllToggles` method which would suffice for the described use-case. Lmk if I'm wrong and there is already a way to access this info.

`useUnleashedContext` is a bit of a misnomer right now as it only returns the update function. Not sure if this was a conscious decision to avoid exposing the internal client and other context components but even having `isEnabled` for access to the flag context outside of hooks would be useful.

Interested to get thoughts on this and I can submit a PR if changes are justified.

**Comment by thomasheartman** [comment]
Hey, @jtaaa 👋🏼 

Thanks for the input! I've got a few followup questions:

> As far as I can tell, this package does not currently support a way to extract the current value of all flags.
By "all flags", do you mean "all flags that exist on the Unleash server" or "all flags that are enabled for this user"?

> This is useful for providing context for A/B testing and analytics. 

What exactly is it you're looking for here? There may be another way of getting what you want. Have you had a look at the [impression data feature](https://docs.getunleash.io/advanced/impression-data), for instance?

> There also seems to be no way to access the underlying unleashed js SDK client which exposes the getAllToggles method which would suffice for the described use-case.

If you're looking for the `UnleashClient` from [the JS Proxy client](https://github.com/Unleash/unleash-proxy-client-js), then it's re-exported from this package, so you can do something like this, as shown in [the installation section of the readme](https://github.com/Unleash/proxy-client-react#installation):

```jsx
import FlagProvider, { UnleashClient } from '@unleash/proxy-client-react';

const config = {
  url: 'https://HOSTNAME/proxy',
  clientKey: 'PROXYKEY',
  refreshInterval: 15,
  appName: 'your-app-name',
  environment: 'dev',
};

const client = new UnleashClient(config);

ReactDOM.render(
  <React.StrictMode>
    <FlagProvider unleashClient={client}>
      <App />
    </FlagProvider>
  </React.StrictMode>,
  document.getElementById('root')
);
```

Because it's the same client as in the JS Proxy client, you'll get access to the `getAllToggles` method etc. 

But you're right in that it doesn't expose a hook to get the currently active Unleash client. That seems like something we might want to consider adding. I'll check in with the team.

> useUnleashedContext is a bit of a misnomer right now as it only returns the update function

I agree that the naming here seems a bit strange. The [Unleash Context](https://docs.getunleash.io/user_guide/unleash_context) is not the same as the `UnleashClient`, but you're right in that it might make more sense that the update function was exposed as a property instead.

> having isEnabled for access to the flag context outside of hooks would be useful.

For sure! As mentioned above, if you instantiate the client yourself, then you can use it wherever.

Does that cover your question? ☺️

**Comment by jtaaa** [comment]
thanks for the detailed response @thomasheartman! that covers it

**Comment by thomasheartman** [comment]
Great; glad to hear it 😄 I'll close this issue for now, then. Feel free to reopen it if you think there's more to do ☺️
