### ISSUE TITLE
Vite: Minified React error in production build

### ISSUE THREAD

**Issue by mcchrish** [Unleash/proxy-client-react#57]
### Describe the bug

This library is hit by a very common issue in Vite ESModule - CommonJS Interop. The problem is best describe in this issue: https://github.com/vitejs/vite/issues/2139

### Steps to reproduce the bug

1. Use Vite and use the react template.
2. `import FlagProvider from "@unleash/proxy-client-react";`
3. Build the app `npm run build && npm run preview`;

**Comment by nunogois** [comment]
Hi @mcchrish thanks for opening the issue and providing detailed information.
Can you confirm that the problem goes away when you `import { FlagProvider } from "@unleash/proxy-client-react";` instead of using the default export?

If that's the case we'll update the docs accordingly and maybe phase out this default export at a later major version (only use named exports).

**Comment by mcchrish** [comment]
Hi @nunogois, yes that's exactly how I worked around it.

**Comment by madhurgarg71** [comment]
Hi @nunogois I am still facing this issue with webpack production build, dev mode is working fine. I am getting the below error:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/7683225/178583211-a1595775-b19d-4fd8-94a0-4447bf14d216.png">

I have tried both default and named import.

**Comment by nunogois** [comment]
Hi @madhurgarg71 - Created a simple CRA demo to try and reproduce this issue, but was unable to:
 - https://github.com/nunogois/proxy-client-react-demo-cra
 - https://proxy-client-react-demo-cra.vercel.app/
 
Would be perfect if you could share an example/steps so we can reproduce it on our side 🙂

**Comment by madhurgarg71** [comment]
Thanks for the demo ! @nunogois  - I can't share the example because it looks like a problem with my project dependencies. I have a custom webpack setup in my project. Does it depend on any specific react version? I am using **React@16.x**. This is happening only with the react SDK; when I tried using directly the javascript SDK it's working fine in prod mode as well but loses the reactivity. I am guessing it's happening because somehow the "ref" inside the **FlagProvider** being set as null and thus the client.current is become null. 

I can share my package.json file and webpack.config if that can help?

**Comment by madhurgarg71** [comment]
@nunogois  here you go

Webpack - https://gist.github.com/madhurgarg71/72fe1e06741f6c41cda7a6fda91a3710
Package.json - https://gist.github.com/madhurgarg71/0ade6734a2a43d85af9a554fff2b7c89

**Comment by madhurgarg71** [comment]
@nunogois  Hey @nunogois, this is resolved now; it was a problem with my code only. Thanks for all the help 🙏🏻
